package init

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

func TestGenerateConfigFile(t *testing.T) {
	// Create temporary directory for testing
	tmpDir, err := os.MkdirTemp("", "conveyor-config-test-")
	require.NoError(t, err)
	defer os.RemoveAll(tmpDir)

	certDir := filepath.Join(tmpDir, "certs")
	err = os.MkdirAll(certDir, 0755)
	require.NoError(t, err)

	tests := []struct {
		name       string
		opts       Options
		force      bool
		setup      func(string) // Function to set up test conditions
		wantErr    bool
		validateConfig func(*testing.T, string)
	}{
		{
			name: "successful config generation with defaults",
			opts: Options{
				AuthEnabled: false,
				APIPort:     8080,
				NATSPort:    4222,
			},
			force: false,
			setup: func(string) {}, // No setup needed
			validateConfig: func(t *testing.T, configPath string) {
				var config ConveyorConfig
				data, err := os.ReadFile(configPath)
				require.NoError(t, err)
				err = yaml.Unmarshal(data, &config)
				require.NoError(t, err)

				assert.Equal(t, "localhost", config.API.Host)
				assert.Equal(t, 8080, config.API.Port)
				assert.Equal(t, "localhost", config.NATS.Host)
				assert.Equal(t, 4222, config.NATS.Port)
				assert.True(t, config.TLS.Enabled)
				assert.Nil(t, config.Auth)
				assert.Equal(t, "http://localhost:3100", config.Loki.Host)
				assert.Equal(t, "http://localhost:2379", config.ETCD.Host)

				// Verify TLS paths
				assert.Equal(t, filepath.Join(certDir, "ca.crt"), config.TLS.CAFile)
				assert.Equal(t, filepath.Join(certDir, "server.crt"), config.TLS.CertFile)
				assert.Equal(t, filepath.Join(certDir, "server-key.pem"), config.TLS.KeyFile)
			},
		},
		{
			name: "successful config generation with auth enabled",
			opts: Options{
				AuthEnabled: true,
				APIPort:     9090,
				NATSPort:    4223,
			},
			force: false,
			setup: func(string) {}, // No setup needed
			validateConfig: func(t *testing.T, configPath string) {
				var config ConveyorConfig
				data, err := os.ReadFile(configPath)
				require.NoError(t, err)
				err = yaml.Unmarshal(data, &config)
				require.NoError(t, err)

				assert.Equal(t, 9090, config.API.Port)
				assert.Equal(t, 4223, config.NATS.Port)
				assert.NotNil(t, config.Auth)
				assert.True(t, config.Auth.Enabled)
				assert.Equal(t, "basic", config.Auth.Method)
			},
		},
		{
			name: "successful config generation with force overwrite",
			opts: Options{
				AuthEnabled: false,
				APIPort:     8080,
				NATSPort:    4222,
			},
			force: true,
			setup: func(configPath string) {
				// Create existing config file
				err := os.WriteFile(configPath, []byte("existing config"), 0644)
				require.NoError(t, err)
			},
			validateConfig: func(t *testing.T, configPath string) {
				// Just verify it was overwritten
				data, err := os.ReadFile(configPath)
				require.NoError(t, err)
				assert.NotEqual(t, "existing config", string(data))
			},
		},
		{
			name: "fail when config exists without force",
			opts: Options{
				AuthEnabled: false,
				APIPort:     8080,
				NATSPort:    4222,
			},
			force: false,
			setup: func(configPath string) {
				// Create existing config file
				err := os.WriteFile(configPath, []byte("existing config"), 0644)
				require.NoError(t, err)
			},
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			configPath := filepath.Join(tmpDir, tt.name+"-conveyor.yml")

			// Setup test conditions
			tt.setup(configPath)

			err := generateConfigFile(configPath, certDir, tt.opts, tt.force)
			if tt.wantErr {
				assert.Error(t, err)
				return
			}

			require.NoError(t, err)
			assert.FileExists(t, configPath)

			// Validate config content
			if tt.validateConfig != nil {
				tt.validateConfig(t, configPath)
			}

			// Verify file contains header comment
			data, err := os.ReadFile(configPath)
			require.NoError(t, err)
			content := string(data)
			assert.Contains(t, content, "# Conveyor CI Configuration File")
			assert.Contains(t, content, "# Generated by 'conveyor init'")
		})
	}
}

func TestGenerateConfigFileCreatesDirs(t *testing.T) {
	// Create temporary directory for testing
	tmpDir, err := os.MkdirTemp("", "conveyor-config-dirs-test-")
	require.NoError(t, err)
	defer os.RemoveAll(tmpDir)

	// Use nested path that doesn't exist
	configPath := filepath.Join(tmpDir, "nested", "path", "conveyor.yml")
	certDir := filepath.Join(tmpDir, "certs")

	opts := Options{
		AuthEnabled: false,
		APIPort:     8080,
		NATSPort:    4222,
	}

	err = generateConfigFile(configPath, certDir, opts, false)
	require.NoError(t, err)

	// Verify directories were created
	assert.DirExists(t, filepath.Dir(configPath))
	assert.FileExists(t, configPath)
}

func TestConveyorConfigStructure(t *testing.T) {
	// Test YAML marshaling/unmarshaling of config structures
	config := ConveyorConfig{
		API: APIConfig{
			Host: "test-host",
			Port: 9999,
		},
		NATS: NATSConfig{
			Host: "nats-host",
			Port: 4444,
		},
		TLS: TLSConfig{
			Enabled:  true,
			CAFile:   "/path/to/ca.crt",
			CertFile: "/path/to/server.crt",
			KeyFile:  "/path/to/server.key",
		},
		Auth: &AuthConfig{
			Enabled: true,
			Method:  "oauth",
		},
		Loki: LokiConfig{
			Host: "http://loki:3100",
		},
		ETCD: ETCDConfig{
			Host: "http://etcd:2379",
		},
	}

	// Marshal to YAML
	yamlData, err := yaml.Marshal(&config)
	require.NoError(t, err)

	// Unmarshal back
	var unmarshaledConfig ConveyorConfig
	err = yaml.Unmarshal(yamlData, &unmarshaledConfig)
	require.NoError(t, err)

	// Verify structure
	assert.Equal(t, config.API.Host, unmarshaledConfig.API.Host)
	assert.Equal(t, config.API.Port, unmarshaledConfig.API.Port)
	assert.Equal(t, config.NATS.Host, unmarshaledConfig.NATS.Host)
	assert.Equal(t, config.NATS.Port, unmarshaledConfig.NATS.Port)
	assert.Equal(t, config.TLS.Enabled, unmarshaledConfig.TLS.Enabled)
	assert.Equal(t, config.TLS.CAFile, unmarshaledConfig.TLS.CAFile)
	assert.Equal(t, config.TLS.CertFile, unmarshaledConfig.TLS.CertFile)
	assert.Equal(t, config.TLS.KeyFile, unmarshaledConfig.TLS.KeyFile)
	assert.NotNil(t, unmarshaledConfig.Auth)
	assert.Equal(t, config.Auth.Enabled, unmarshaledConfig.Auth.Enabled)
	assert.Equal(t, config.Auth.Method, unmarshaledConfig.Auth.Method)
	assert.Equal(t, config.Loki.Host, unmarshaledConfig.Loki.Host)
	assert.Equal(t, config.ETCD.Host, unmarshaledConfig.ETCD.Host)
}

func TestConveyorConfigWithoutAuth(t *testing.T) {
	// Test config without auth section
	config := ConveyorConfig{
		API: APIConfig{
			Host: "localhost",
			Port: 8080,
		},
		NATS: NATSConfig{
			Host: "localhost",
			Port: 4222,
		},
		TLS: TLSConfig{
			Enabled: true,
		},
		// Auth intentionally omitted
		Loki: LokiConfig{
			Host: "http://localhost:3100",
		},
		ETCD: ETCDConfig{
			Host: "http://localhost:2379",
		},
	}

	// Marshal to YAML
	yamlData, err := yaml.Marshal(&config)
	require.NoError(t, err)

	// Verify auth section is not present in YAML
	yamlString := string(yamlData)
	assert.NotContains(t, yamlString, "auth:")

	// Unmarshal back
	var unmarshaledConfig ConveyorConfig
	err = yaml.Unmarshal(yamlData, &unmarshaledConfig)
	require.NoError(t, err)

	// Verify auth is nil
	assert.Nil(t, unmarshaledConfig.Auth)
}