package init

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// ConveyorConfig represents the structure of conveyor.yml
type ConveyorConfig struct {
	API  APIConfig  `yaml:"api"`
	NATS NATSConfig `yaml:"nats"`
	TLS  TLSConfig  `yaml:"tls"`
	Auth *AuthConfig `yaml:"auth,omitempty"`
	Loki LokiConfig `yaml:"loki"`
	ETCD ETCDConfig `yaml:"etcd"`
}

// APIConfig holds API server configuration
type APIConfig struct {
	Host string `yaml:"host"`
	Port int    `yaml:"port"`
}

// NATSConfig holds NATS server configuration
type NATSConfig struct {
	Host string `yaml:"host"`
	Port int    `yaml:"port"`
}

// TLSConfig holds TLS configuration
type TLSConfig struct {
	Enabled    bool   `yaml:"enabled"`
	CAFile     string `yaml:"ca_file"`
	CertFile   string `yaml:"cert_file"`
	KeyFile    string `yaml:"key_file"`
}

// AuthConfig holds authentication configuration
type AuthConfig struct {
	Enabled bool   `yaml:"enabled"`
	Method  string `yaml:"method"`
}

// LokiConfig holds Loki configuration
type LokiConfig struct {
	Host string `yaml:"host"`
}

// ETCDConfig holds ETCD configuration
type ETCDConfig struct {
	Host string `yaml:"host"`
}

// generateConfigFile creates a conveyor.yml configuration file
func generateConfigFile(configPath, certDir string, opts Options, force bool) error {
	// Check if config file already exists
	if !force && fileExists(configPath) {
		return fmt.Errorf("configuration file already exists: %s (use --force to overwrite)", configPath)
	}

	// Ensure parent directory exists
	if err := ensureParentDir(configPath); err != nil {
		return err
	}

	// Create configuration structure
	config := ConveyorConfig{
		API: APIConfig{
			Host: "localhost",
			Port: opts.APIPort,
		},
		NATS: NATSConfig{
			Host: "localhost",
			Port: opts.NATSPort,
		},
		TLS: TLSConfig{
			Enabled:  true,
			CAFile:   filepath.Join(certDir, "ca.crt"),
			CertFile: filepath.Join(certDir, "server.crt"),
			KeyFile:  filepath.Join(certDir, "server-key.pem"),
		},
		Loki: LokiConfig{
			Host: "http://localhost:3100",
		},
		ETCD: ETCDConfig{
			Host: "http://localhost:2379",
		},
	}

	// Add auth configuration if enabled
	if opts.AuthEnabled {
		config.Auth = &AuthConfig{
			Enabled: true,
			Method:  "basic", // Default auth method
		}
	}

	// Marshal to YAML
	yamlData, err := yaml.Marshal(&config)
	if err != nil {
		return fmt.Errorf("failed to marshal configuration to YAML: %w", err)
	}

	// Write configuration file
	file, err := os.OpenFile(configPath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0644)
	if err != nil {
		return fmt.Errorf("failed to create configuration file %s: %w", configPath, err)
	}
	defer file.Close()

	// Write header comment
	header := `# Conveyor CI Configuration File
# Generated by 'conveyor init'
# 
# This file contains the configuration for your Conveyor CI instance.
# Modify as needed for your environment.

`
	if _, err := file.WriteString(header); err != nil {
		return fmt.Errorf("failed to write configuration header: %w", err)
	}

	// Write YAML content
	if _, err := file.Write(yamlData); err != nil {
		return fmt.Errorf("failed to write configuration content: %w", err)
	}

	return nil
}